import uuid
from datetime import date, datetime
from enum import Enum

from sqlalchemy import Date, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.sqlite import JSON

from app.database import Base


class MealPlanStatus(str, Enum):
    draft = "draft"           # generated, not yet confirmed by user
    confirmed = "confirmed"   # user confirmed → inventory has been deducted
    completed = "completed"   # all days have passed


class MealSlot(str, Enum):
    breakfast = "breakfast"
    lunch = "lunch"
    dinner = "dinner"


class MealPlan(Base):
    """
    A multi-day meal plan generated by the agent.

    meals: [{date: YYYY-MM-DD, slot: dinner, recipe_id: uuid, servings: int}]
    inventory_snapshot: state of inventory at the time of planning (for audit/redo)
    constraint_summary: what constraints the agent applied (for display to user)
    """
    __tablename__ = "meal_plans"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("user_profiles.id", ondelete="CASCADE"), index=True
    )

    days: Mapped[int] = mapped_column(Integer, nullable=False)
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    end_date: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default=MealPlanStatus.draft, index=True
    )

    # Core payload — list of meal assignments
    meals: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    # Snapshot of inventory at planning time (for reproducibility)
    inventory_snapshot: Mapped[list] = mapped_column(JSON, default=list)

    # Human-readable summary of what the agent did: e.g. "prioritized spinach (exp 2 days)"
    constraint_summary: Mapped[dict] = mapped_column(JSON, default=dict)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    user: Mapped["UserProfile"] = relationship(back_populates="meal_plans")  # noqa: F821
    shopping_list: Mapped["ShoppingList | None"] = relationship(  # noqa: F821
        back_populates="meal_plan", uselist=False, cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<MealPlan id={self.id} days={self.days} status={self.status}>"
